Include in Parser a Review Manager
jessesquires/swift-proposal-analyzer pull request #12
Opened 2017-03-24 02:50 UTC by digoreis

I include Review Manager in Parser and Proposal file. I prepared to recipe multiple Reviewers like Authors. 

Also, include a reviewBy in the proposal to help filter.

2017-03-24 04:00 UTC, unnamedd approved these changes

2017-03-24 15:58 UTC, jessesquires requested changes
Thanks so much @digoreis ! 🎉 

Overall this looks great, just a few minor things to address.

Also -- could we revert the proposal/submodule changes? That will make this cleaner for git history.

2017-03-24 15:58 UTC, jessesquires commented on Sources/Parser.swift
> +    dump(Proposal(title: title,
nit: remove?

2017-03-24 15:58 UTC, jessesquires commented on Sources/Parser.swift
> +                    )
let's put `)` on the same line to follow existing project style 😄

2017-03-24 15:58 UTC, jessesquires commented on Sources/Proposal.swift
> +    public func reviewBy(_ reviewerName: String) -> Bool {
let's make these `reviewedBy` 😄

2017-03-24 15:58 UTC, jessesquires commented on Sources/ReviewManager.swift
> +//
let's copy the project comment headers

2017-03-24 17:59 UTC, digoreis commented
Hi @jessesquires, I updated the pull request. To fix the proposal in git history I remove of the project and include de directory in the gitignore file. But the better solution is to remove a copy in the update, creating a symbolic link to the swift-proposal directory. 

And I fixed the others comments in Code Review. Sorry the dump, I forget to remove the dump 😢.

2017-03-27 15:52 UTC, jessesquires commented on .gitignore
> +swift-proposal-analyzer.playground/Resources/proposals/
we don't want to do this, or delete the proposals... 😅

2017-03-27 15:54 UTC, jessesquires commented
Thanks @digoreis !

Looks like more unrelated changes were added. We definitely don't want to change the `gitignore`.

Do you want to re-pull the repo, and do a fresh PR with only the changes to the framework source files? 

Just *don't* run the `update_proposals.sh` script and it should be ok.

2017-03-28 21:15 UTC, closed without merging

2017-04-03 01:35 UTC, jessesquires commented
Hey @digoreis - did you want open up a new PR for this? 😄