Include parse to Bug field in Proposal
jessesquires/swift-proposal-analyzer pull request #16
Opened 2017-04-05 20:37 UTC by digoreis

- Include field Bug in Proposal;

2017-04-06 01:37 UTC, unnamedd approved these changes

2017-04-06 23:23 UTC, jessesquires commented on Sources/Bug.swift
> +    public let code: String
is this the `SR-0000` number? what about renaming this `srNumber` ?

2017-04-06 23:24 UTC, jessesquires commented on Sources/Bug.swift
> +/// Represents a review manager for a proposal.
🤔

2017-04-06 23:24 UTC, jessesquires requested changes
Thanks @digoreis !

A couple small things to address

2017-04-07 17:57 UTC, digoreis commented on Sources/Bug.swift
> +/// Represents a review manager for a proposal.
😞

2017-04-08 00:55 UTC, merged

2017-04-08 00:55 UTC, jessesquires commented
Thanks @digoreis !