Include Decision Notes in proposal
jessesquires/swift-proposal-analyzer pull request #17
Opened 2017-04-06 00:06 UTC by digoreis

-Include Decision Notes in Proposal;
closes #2

2017-04-06 01:35 UTC, unnamedd approved these changes

2017-04-06 23:29 UTC, jessesquires requested changes
Thanks @digoreis ! 🎉 

Just a few things to address!

2017-04-06 23:29 UTC, jessesquires commented on Sources/DecisionNote.swift
> +public struct DecisionNote {
let's rename `DecisionNotes`

2017-04-06 23:29 UTC, jessesquires commented on Sources/DecisionNote.swift
> +    public let title: String
how about `text` instead?

2017-04-06 23:29 UTC, jessesquires commented on Sources/DecisionNote.swift
> +/// Represents a review manager for a proposal.
fix doc comment

2017-04-06 23:29 UTC, jessesquires commented on Sources/DecisionNote.swift
> +        return lhs.title == rhs.title
this should also compare URL

2017-04-06 23:29 UTC, jessesquires commented on Sources/DecisionNote.swift
> +        return title.hashValue
also include `URL`

2017-04-07 17:54 UTC, digoreis commented on Sources/DecisionNote.swift
> +/// Represents a review manager for a proposal.
😞

2017-04-07 17:54 UTC, digoreis commented on Sources/DecisionNote.swift
> +    public let title: String
Ok!

2017-04-07 17:55 UTC, digoreis commented on Sources/DecisionNote.swift
> +        return lhs.title == rhs.title
In this case I think we'd better use a URL, it makes more sense. Correct?

2017-04-08 00:57 UTC, jessesquires commented
Thanks for updating @digoreis ! 👍 Looks good now, except there are conflicts to resolve since merging #16 😅

2017-04-10 15:45 UTC, jessesquires commented
thanks so much @digoreis ! 💯

2017-04-10 15:46 UTC, merged